using DesignPattern.Creational.Factory;
using DesignPattern.Creational.AbstractFactory;
using DesignPattern.Creational.Singelton;
using DesignPattern.Creational.Prototype;
using DesignPattern.Creational.Builder;
using DesignPattern.Structural.Adapter;
using DesignPattern.Structural.Facade;
using DesignPattern.Structural.Decorator;
using DesignPattern.Structural.Bridge;
using DesignPattern.Structural.Proxy;
using DesignPattern.Structural.FlyWeight;
using DesignPattern.Structural.Composite;
using DesignPattern.Behavioural.Stratergy;
using DesignPattern.Behavioural.Observer;
using DesignPattern.Behavioural.Command;
using DesignPattern.Behavioural.TemplateMethod;
using DesignPattern.Behavioural.State;
using DesignPattern.Behavioural.Iterator;


// FactoryClient.Invoke();
// AbstractFactoryClient.Invoke();
// SingeltonClient.Invoke();
// PrototypeClient.Invoke();
// BuilderClient.Invoke();
// AdapterClient.Invoke();
// FacadeClient.Invoke();
// DecoratorClient.Invoke();
// BridgeClient.Invoke();
// ProxyClient.Invoke();
// FlyweightClient.Invoke();
// CompositeClient.Invoke();
// StrategyClient.Invoke();
// ObserverClient.Invoke();
// CommandClient.Invoke();
// TemplateMethodClient.Invoke();
// StateClient.Invoke();
IteratorClient.Invoke();